env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'

ignorePatterns:
  - '/dist'

rules:
  # Formatting done by Prettier
  function-paren-newline: 0
  no-confusing-arrow: 0
  implicit-arrow-linebreak: 0
  object-curly-newline: 0
  operator-linebreak: 0
  # END
  consistent-return: 0
  import/prefer-default-export: 0
  no-console: 1
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - objects: only-multiline
      arrays: only-multiline
      functions: ignore
  no-param-reassign:
    - error
    - props: false
  no-return-assign:
    - error
    - except-parens
  max-len:
    - error
    - ignoreComments: true
      code: 100
